name: first

on: 
  push:
    branches:
      - develop
      - main
  pull_requests:
    branches:
      - main
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step One
      uses: actions/checkout@v4
    - name: Step Two
      run: env | sort 
  job2:
    needs: [job1] # Job2 dependent on Job1
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step One
      uses: actions/checkout@v4
    - name: Step Two
      run: "Get-ChildItem Env: | Sort-Object Name"
  job3:
    needs: [job2] # Job3 dependent on Job2
    name: Third job
    runs-on: windows-latest
    steps:
    - name: Step One
      uses: actions/checkout@v4
    - name: Step Two
      run: Write-Output "Hello GitHub Actions"

